name: C/C++ CI (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Tree
        uses: actions/checkout@v3

      - name: Setup folder directories
        run: |
          mkdir build
          mkdir build\x86
          mkdir build\x64

      - name: Build xpmgr (x86)
        run: g++ -m32 -o build\x86\xpmgr_x86 xpmgr.cpp -lole32 -luuid -loleaut32

      - name: Build xpmgr (x64)
        run: g++ -o build\x64\xpmgr_x64 xpmgr.cpp -lole32 -luuid -loleaut32

      - name: Upload build artifact (x86)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: xpmgr (x86)
          path: .\build\x86
          
      - name: Upload build artifact (x64)
        uses: actions/upload-artifact@v3.1.2
        with:
          name: xpmgr (x64)
          path: .\build\x64
